### ISSUE TITLE
VXBF count > IXBF count, some data not processed

### ISSUE THREAD

**Issue by Demonslayerx8** [kotcrab/fate-explorer#2]
Seems like meshes that give this error on export loses their rigging, or have rigging messed up. This is all on PC Fate Extella Umbra Star.

Objects
GIM_SP_SV02_SKY
CH02_MYROOM_A
CH02_MYROOM_B
CH02_MYROOM_C

Char's so far I've seen this on is..
SV1500
SV1560 (DLC)

Also, models from the switch version of the game doesn't seem to load anymore, even tho it used to. Willing to provide files if needed.

**Comment by kotcrab** [comment]
I'll look into this though this error means that there is vertex buffer without matching indicies buffer and I really don't know what to do about it. Maybe the rigging issue is unrelated to it though.

The lastest script version has to detect PC and Vita models so I can see why Switch won't work. DM me on Discord for the files: Kotcrab#0044

**Comment by kotcrab** [comment]
`SV1500` and `SV1560` have some mesh parts encoded in different format which does not appear to have vertex bone and weight data. It's easy enough to fix manually after exporting. Maybe someone will figure out how it's handled, for now there's nothing more I can do.

The `VXBF count > IXBF count` error is unrelated to this. Switch models work again fixed in 58dc5f5b841860013d1ebc78d549d0fe35bb6d7e
